version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: agritrade-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agritrade
    volumes:
      - mongodb_data:/data/db
    networks:
      - agritrade-network

  backend:
    build: ./backend
    container_name: agritrade-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/agritrade
      JWT_SECRET: your-super-secure-jwt-secret-key-minimum-32-characters
      NODE_ENV: production
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - agritrade-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: agritrade-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - agritrade-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  agritrade-network:
    driver: bridge
